language: csharp
sudo: required
mono: none
dotnet: 1.0.3
dist: trusty
solution: verbose-test.sln
script:
- ./build.sh --quiet verify
- dotnet test /home/travis/build/mrBoie/verbose-test\Unittest\Unittest.csproj
